name: blizz_chat
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.1.3 <4.0.0'

dependencies:
  cloud_firestore: ^4.9.3
  firebase_auth: ^4.10.1
  firebase_core: ^2.16.0
  flutter:
    sdk: flutter
  google_fonts: ^6.1.0 
  go_router: ^11.1.4
  json_serializable: ^6.7.1
  json_annotation: ^4.8.1
  flutter_riverpod: ^2.4.4
  riverpod_annotation: ^2.2.1
  firebase_storage: ^11.3.1
  freezed_annotation: ^2.4.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner: ^2.4.6
  riverpod_generator: ^2.3.5
  custom_lint: ^0.5.4
  riverpod_lint: ^2.3.2
  freezed: ^2.4.5

flutter:
  uses-material-design: true
