name: blizz_chat
description: A Very Good Project created by Very Good CLI.
version: 1.0.0+1
publish_to: none

environment:
  sdk: ^3.4.0

dependencies:
  auto_route: ^8.3.0
  bloc: ^8.1.4
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.6
  flutter_localizations:
    sdk: flutter
  intl: 0.19.0
  # flutter_gen: any
  freezed_annotation: ^2.4.4
  json_annotation: ^4.9.0
  chopper: ^8.0.1+1
  get_it: ^7.7.0
  shared_preferences: ^2.2.3
  injectable: ^2.4.4

dev_dependencies:
  auto_route_generator: ^8.1.0
  bloc_test: ^9.1.7
  build_runner: ^2.4.11
  flutter_test:
    sdk: flutter
  freezed: ^2.5.2
  json_serializable: ^6.8.0
  mocktail: ^1.0.4
  very_good_analysis: ^6.0.0
  injectable_generator: ^2.6.2
  chopper_generator: ^8.0.1

flutter:
  uses-material-design: true
  generate: true
