version: '3.9'

services:
  mongo:
    image: mongo
    container_name: "mongo"
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    volumes:
      - ~/apps/mongodb:/data/db
    ports:
      - 27017:27017

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
      ME_CONFIG_MONGODB_URL: mongodb://root:example@mongo:27017/
      ME_CONFIG_BASICAUTH: false


# version: '3.9'

# services:
#   backend:
#     build:
#       context: ./
#       dockerfile: Dockerfile
#     container_name: blizz-chat-backend
#     depends_on:
#       - mongo
#     environment:
#       MONGODB_URI: mongodb://root:example@mongo:27017/BlizzChat
#     ports:
#       - 3000:3000

#   mongo:
#     image: mongo
#     container_name: mongo
#     restart: always
#     environment:
#       MONGO_INITDB_ROOT_USERNAME: root
#       MONGO_INITDB_ROOT_PASSWORD: example
#     volumes:
#       - mongo_data:/data/db
#     ports:
#       - 27017:27017

# volumes:
#   mongo_data:
