// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
///
///

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBnXEIe8JLAfeizkhMTw84Lhm7JdtzcpSM',
    appId: '1:446227026702:web:87d5bad5e84bdda3977d5f',
    messagingSenderId: '446227026702',
    projectId: 'blizz-chat-61069',
    authDomain: 'blizz-chat-61069.firebaseapp.com',
    storageBucket: 'blizz-chat-61069.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBiFK9uTu7gQpmC2n_GdHaPb31_tHocccE',
    appId: '1:446227026702:android:d6a664fef9fea0c1977d5f',
    messagingSenderId: '446227026702',
    projectId: 'blizz-chat-61069',
    storageBucket: 'blizz-chat-61069.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyADZZKfU6DJmJ-IJGtPjXwyFzI-kWu7k1Y',
    appId: '1:446227026702:ios:20dd32ed3d8147c6977d5f',
    messagingSenderId: '446227026702',
    projectId: 'blizz-chat-61069',
    storageBucket: 'blizz-chat-61069.appspot.com',
    iosBundleId: 'com.example.blizzChat',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyADZZKfU6DJmJ-IJGtPjXwyFzI-kWu7k1Y',
    appId: '1:446227026702:ios:1824cd40b7d67e74977d5f',
    messagingSenderId: '446227026702',
    projectId: 'blizz-chat-61069',
    storageBucket: 'blizz-chat-61069.appspot.com',
    iosBundleId: 'com.example.blizzChat.RunnerTests',
  );
}
